---
- name: "copy the package to ec2"
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    mode: '0755'

- name: "untar the file"
  become: yes
  shell: tar -zxvf ~/artifact.tar.gz

- name: "start the app"
  shell: |
    cd ~/
    export TYPEORM_ENTITIES=./src/modules/domain/**/entities/*.entity.ts
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=postgres123
    export TYPEORM_DATABASE=postgres
    export TYPEORM_PORT=5432
    export TYPEORM_HOST=database-2.cugdpktsyisy.us-east-1.rds.amazonaws.com
    export TYPEORM_MIGRATIONS=./src/migrations/*.ts
    export TYPEORM_MIGRATIONS_DIR=./src/migrations
    export TYPEORM_CONNECTION=postgres
    sudo mkdir .pm2
    sudo chown -R ubuntu:ubuntu .pm2
    npm install
    pm2 start npm -- start
